### ISSUE TITLE
MNP_US_MC Creation

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#10]
We need US Army multicam faction

Uniform 1 - MNP_CombatUniform_DS_A
Uniform 2 - MNP_CombatUniform_DS_B

Vest 1 - MNP_Vest_DS_1_ARM
Vest 2 - MNP_Vest_DS_2_ARM

Helmet - MNP_Helmet_DS

Armed with the regular M4A1 pattern of weapons:

M4A1
M4A1 M203
M249
M240
AT4 for RAT

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/1734b3e0c82543418d3ccdd677dafe0c37fc3ec6
