### ISSUE TITLE
 MNP_CH_WD Creation

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#12]
Woodland China faction needs resurrected.

Uniform - MNP_CombatUniform_China_J

Vest - MNP_Vest_ChinaH_J_ARM
Vest 2 - MNP_Vest_ChinaH_J2_ARM

Helmet - MNP_Helmet_PAGST_CNJ

Same weapons as the the rest of China.

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/7ac48dae9bb2828059802327cedcba7abcb77dbc
