### ISSUE TITLE
MNP_RU_VDV_DE Vests

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#13]
Wrong vests for all of the units:

Vest 1 - MNP_Vest_RU_D1_ARM
Vest 2 - MNP_Vest_RU_D2_ARM

Incorrect soft cover for the medic, currently has a boonie in woodland:

Cap - MNP_MilCap_RU_D
Boonie - MNP_Boonie_RU_D

Helmets are also wrong:

Helmet - MNP_Helmet_PAGST_RD

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/9d7dea34f3e370ab967dd3874681a79b0db05d6b
