### ISSUE TITLE
MNP_KOR_WD Vests & Helmets

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#14]
Only the team leader has a vest rest of the units have none.

Vest in use by the leader - V_Chestrig_rgr

Some of the new SLA vests may look better.

Also helmets for all need to be changed to the Soviet style - CUP_H_SLA_Helmet

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/ee0c0069687aac7cd8909154106d9c4e62b78c9f

Need vest classnames

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/8afb07fede5407303ffcadf3ca3b19913c567a1f
