### ISSUE TITLE
IND Faction Names

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#21]
MNP_MIL_WD class should be MNP_LVM_WD
MNP_MIL_DE class should be MNP_LVM_DE

Change MNP_IRE_WD display name to be "Ireland Defence Forces Woodland"
Change MNP_IRE_DE display name to be "Ireland Defence Forces Desert"

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/f950c33409844aea6752a0bf814f19abaeb277d9
