### ISSUE TITLE
Blufor Faction Names

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#22]
MNP_US_SCO  class should be MNP_US_RAN

MNP_US_SCO display name should be "United Sates Army Rangers"

MNP_ROKMC class should be MNP_ROK_SEAL

MNP_ROKMC display name should be "Republic of Korea Seals"

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/f950c33409844aea6752a0bf814f19abaeb277d9
