### ISSUE TITLE
Opfor Faction Names

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#23]
MNP_CH_WD class should be MNP_CH_UNI

MNP_CH_MAR display name should be "Chinese PLA Naval Marines"

MNP_IRN_WD_IRGC class should become MNP_IRN_RG

MNP_IRN_WD_IRGC display name should become Iranian Revolutionary Guards

MNP_IRN_DE_IRGC class should be MNP_IRN

MNP_IRN_DE_IRGC display name should be Iranian Army

MNP_RU_AIR display name should be "Russian (Soviet) Infantry Airborne"

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/f950c33409844aea6752a0bf814f19abaeb277d9
