### ISSUE TITLE
MNP_RU_AIR Vests

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#26]
Vests should be replaced with:

Rifleman | CUP_V_RUS_Smersh_1
AR | CUP_V_O_Ins_Carrier_Rig_MG
MG | CUP_V_O_Ins_Carrier_Rig_MG
RAT | CUP_V_RUS_Smersh_1
Medic | CUP_V_O_Ins_Carrier_Rig_Light
FTL | CUP_V_RUS_Smersh_2

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/e0643b19d3781269fd22cc1436d676b76b8464f6
