### ISSUE TITLE
Germany Removal

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#27]
List of the classnames that can be hidden:

Uniform 1 - MNP_CombatUniform_Germany
Uniform 2 - MNP_CombatUniform_Germany_S
Uniform 3 - MNP_CombatUniform_Germany_SD
Uniform 4 - MNP_CombatUniform_Germany_D

Vest 1 - MNP_Vest_Germany_2_ARM
Vest 2 - MNP_Vest_Germany_D2_ARM
Vest 3 - MNP_Vest_Germany_D_ARM
Vest 4 - MNP_Vest_Germany_ARM

Headgear 1 - MNP_Boonie_GER_T
Headgear 2 - MNP_Boonie_GER_D
Headgear 3 - MNP_Helmet_Germany
Headgear 4 - MNP_Helmet_Germany_D

I don't think we have backpacks to worry about for the MNP Germans.

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/71841ace5fdf2c5d0c6b504e1dc651b92383c8d0
