### ISSUE TITLE
Update Iran Republican Guard

### ISSUE THREAD

**Issue by Cyruz143** [Cyruz143/mnp_units#4]
Currently a "Woodland" and Desert version. Update Woodland to have different gear as it's not really woodland! Will need to rename and update faction.

```
Rifle - CUP_arifle_AKM
Crew / Medic Carbine - CUP_arifle_AKMS
GL Rifle - CUP_arifle_AKM_GL
Rifle Ammo - CUP_30Rnd_762x39_AK47_M

AR - CUP_arifle_RPK74
AR Ammo - CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M

MG - CUP_lmg_PKM
MG Ammo - CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M

Dispose AT - CUP_launch_RPG18

Non Dispose AT - CUP_launch_RPG7V
HEAT - CUP_PG7VM_M
HE - CUP_OG7_M
```

**Comment by dancemoox** [comment]
Uniforms for Revolutionary Guard (not Republican that's Iraq)

Uniform - MNP_CombatUniform_IR_BSJ_A
Uniform Jumper Sleeves - MNP_CombatUniform_IR_BSJ_Med_B
Uniform Jumper - MNP_CombatUniform_IR_BSJ_Med

Helmet - MNP_Helmet_PAGST_IBSJ

Republican Guard Desert group will need renamed to be Iranian Army.

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/1c55953dbcb3986766f809fb9189aac90030a29b
