### ISSUE TITLE
Weapons review

### ISSUE THREAD

**Issue by Cyruz143** [Cyruz143/mnp_units#6]
I've only used base class weapons for now.

Ideally some prebuilt weapon classes with optics might be good for AI

**Comment by dancemoox** [comment]
MNP_IDF needs looked at. AR should be M249 and AT should be SMAW or LAW.

**Comment by Cyruz143** [comment]
IDF: https://github.com/Cyruz143/mnp_units/commit/3a54d2788dd4c75fec85aea467c290cb1fb98dd2
