### ISSUE TITLE
US Rangers Uniforms

### ISSUE THREAD

**Issue by dancemoox** [Cyruz143/mnp_units#9]
MNP_US_RAN (formerly MNP_US_RAN_SCO) need uniforms switched to the correct multicam.

Uniform 1 - MNP_CombatUniform_DS_A
Uniform 2 - MNP_CombatUniform_DS_B

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/mnp_units/commit/9fa09888dbf3e778cfa0b7afc7e15a589bbbefd0
